language: java

jdk:
- oraclejdk8

sudo: required

env:
  global:
  - IMAGE_NAME=spark-k8s

addons:
  apt:
    update: true

matrix:
  include:
  - services: docker
    env:
    - SPARK_VERSION=master
    - HADOOP_VERSION=3.2.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true
  - services: docker
    env:
    - SPARK_VERSION=2.3.4
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
  - services: docker
    env:
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true

before_install:
- sudo apt-get install --no-install-recommends -y python python-setuptools

before_script:
- ln -s "$(pwd)" "/tmp/$(basename "$(pwd)")"
- cd "/tmp/$(basename "$(pwd)")"
  
script:
- travis_wait 60 bash make-distribution.sh"

deploy:
  provider: script
  script: bash push-images.sh
  on:
    branch: master

branches:
  only:
  - master
