language: java

jdk:
- openjdk8

dist: xenial

sudo: required

env:
  global:
  - IMAGE_NAME=spark-k8s

# This is critical because of the way -f is interpreted in newer version with
# regards to the build Docker context path
addons:
  apt:
    update: true
    packages:
    - docker-ce
    - python
    - python-setuptools

matrix:
  include:
  - services: docker
    env:
    - SPARK_VERSION=master
    - HADOOP_VERSION=3.2.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true
  - services: docker
    env:
    - SPARK_VERSION=2.3.4
    - HADOOP_VERSION=2.7.3
    - WITH_HIVE=true
    - WITH_PYSPARK=true
  - services: docker
    env:
    - SPARK_VERSION=2.4.4
    - HADOOP_VERSION=3.1.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true

before_script:
- docker --version

script:
- travis_wait 60 bash make-distribution.sh

deploy:
  provider: script
  script: bash push-images.sh
  on:
    branch: master

branches:
  only:
  - master
