language: java

jdk:
- oraclejdk8

sudo: required

env:
  global:
  - DOCKER_REPO=${DOCKER_USERNAME}/spark-k8s

matrix:
  include:
  - services: docker
    env:
    - SPARK_VERSION=2.4.3
    - HADOOP_VERSION=3.1.0
    - WITH_HIVE=true
    - WITH_PYSPARK=true

before_install:
- sudo apt-get install --no-install-recommends -y python python-setuptools
addons:
  apt:
    update: true
  
script:
- bash make-distribution.sh

deploy:
  provider: script
  script: bash push-images.sh
  # on:
  #   branch: master

branches:
  only:
  - master
