# This Dockerfile is meant to be only used by make-distribution.sh for copying
# pyspark directory for >= Spark 2.4
ARG IMAGE_NAME
ARG TAG_NAME
FROM ${IMAGE_NAME}-py:${TAG_NAME}

COPY ./spark/python/pyspark "${SPARK_HOME}/python/pyspark"
