name: CI

on:
  push:
    branches:
    - master
    - v*
  pull_request:
    branches:
    - master
    - v*

jobs:
  build:
    strategy:
      matrix:
        version:
        - spark:        "3.4.1"
          java:         "8"
          hadoop:       "3.3.4"
          scala:        "2.12"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.4.1"
          java:         "8"
          hadoop:       "3.3.4"
          scala:        "2.13"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.4.1"
          java:         "11"
          hadoop:       "3.3.4"
          scala:        "2.12"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.4.1"
          java:         "11"
          hadoop:       "3.3.4"
          scala:        "2.13"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.5.2"
          java:         "8"
          hadoop:       "3.3.4"
          scala:        "2.12"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.5.2"
          java:         "8"
          hadoop:       "3.3.4"
          scala:        "2.13"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.5.2"
          java:         "8"
          hadoop:       "3.4.0"
          scala:        "2.12"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.5.2"
          java:         "8"
          hadoop:       "3.4.0"
          scala:        "2.13"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.5.2"
          java:         "11"
          hadoop:       "3.3.4"
          scala:        "2.12"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.5.2"
          java:         "11"
          hadoop:       "3.3.4"
          scala:        "2.13"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.5.2"
          java:         "11"
          hadoop:       "3.4.0"
          scala:        "2.12"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.5.2"
          java:         "11"
          hadoop:       "3.4.0"
          scala:        "2.13"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.5.2"
          java:         "17"
          hadoop:       "3.3.4"
          scala:        "2.12"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.5.2"
          java:         "17"
          hadoop:       "3.3.4"
          scala:        "2.13"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.5.2"
          java:         "17"
          hadoop:       "3.4.0"
          scala:        "2.12"
          with_hive:    "true"
          with_pyspark: "true"
        - spark:        "3.5.2"
          java:         "17"
          hadoop:       "3.4.0"
          scala:        "2.13"
          with_hive:    "true"
          with_pyspark: "true"
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: "spark-k8s"
      SELF_VERSION: "v4"
      SPARK_VERSION: "${{ matrix.version.spark }}"
      HADOOP_VERSION: "${{ matrix.version.hadoop }}"
      SCALA_VERSION: "${{ matrix.version.scala }}"
      JAVA_VERSION: "${{ matrix.version.java }}"
      WITH_HIVE: "${{ matrix.version.with_hive }}"
      WITH_PYSPARK: "${{ matrix.version.with_pyspark }}"
    steps:
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '${{ matrix.version.java }}'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install tera-cli
      run: |-
        wget https://github.com/guangie88/tera-cli/releases/download/v0.4.1/tera-cli-v0.4.1-x86_64-unknown-linux-musl.tar.gz
        tar xf tera-cli-*.tar.gz
        mv tera-cli*/tera /tmp/tera
        rm tera-cli-*.tar.gz
    - name: Check differences between ci.yml and ci.yml.tmpl
      run: |-
        cp .github/workflows/ci.yml .github/workflows/ci.yml.backup
        TERA=/tmp/tera ./templates/apply-vars.sh
        if ! diff .github/workflows/ci.yml .github/workflows/ci.yml.backup; then echo "ci.yml.tmpl and ci.yml differs!" && exit 1; fi
    - name: Check shell scripts
      run: |-
        shellcheck templates/apply-vars.sh
        shellcheck push-images.sh
    - name: Install setuptools and wheel
      run: python3 -m pip install setuptools wheel
    - name: Build Docker image
      run: MAVEN_OPTS="-Xss2M" bash make-distribution.sh
    - name: Push Docker image
      run: bash push-images.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_ORG: ${{ secrets.IMAGE_ORG }}
      if: github.event_name == 'push'
